# Generated by Django 5.1.2 on 2024-10-23 21:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Produit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=255)),
                (
                    "description",
                    models.TextField(blank=True, max_length=255, null=True),
                ),
                ("prix", models.DecimalField(decimal_places=2, max_digits=10)),
                ("quantite", models.PositiveIntegerField()),
                ("date_ajout", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
